name: Sync upstream (preserve local changes)

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: 'How to apply changes (pr or push)'
        required: false
        default: 'push'
        type: choice
        options:
          - pr
          - push
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

permissions:
  contents: write
  pull-requests: write

env:
  # 固定上游与分支（可按需修改）
  UPSTREAM_REPO: Decohererk/DecoTV
  UPSTREAM_BRANCH: main
  TARGET_BRANCH: main
  # 冲突策略：-X ours（保留本地改动）
  MERGE_PREFERENCE: ours

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Prepare defaults
        id: defaults
        shell: bash
        run: |
          set -e
          # 固定参数已通过 env 传入，这里仅向环境导出
          echo "UPSTREAM_REPO=${UPSTREAM_REPO}" >> "$GITHUB_ENV"
          echo "UPSTREAM_BRANCH=${UPSTREAM_BRANCH}" >> "$GITHUB_ENV"
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> "$GITHUB_ENV"
          echo "MERGE_PREFERENCE=${MERGE_PREFERENCE}" >> "$GITHUB_ENV"
          # 事件类型：schedule 强制 push；手动触发可通过 inputs 覆盖，默认 push
          if [ "${GITHUB_EVENT_NAME}" = "schedule" ]; then
            echo "RUN_MODE=push" >> "$GITHUB_ENV"
          else
            echo "RUN_MODE=${{ github.event.inputs.run_mode || 'push' }}" >> "$GITHUB_ENV"
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote remove upstream || true
          git remote add upstream "https://github.com/${UPSTREAM_REPO}.git"
          git fetch upstream "${UPSTREAM_BRANCH}"

      - name: Merge upstream into target (prefer local changes on conflicts)
        id: merge
        shell: bash
        run: |
          set -e
          git checkout "${TARGET_BRANCH}"
          # Make sure local is up to date
          git pull --ff-only origin "${TARGET_BRANCH}" || true

          # Strategy: prefer local when conflicts, so upstream updates won't override your customizations
          STRAT="${MERGE_PREFERENCE}"
          echo "Using merge preference: ${STRAT}"
          git merge --no-edit -X "${STRAT}" "upstream/${UPSTREAM_BRANCH}" || true

          # Detect if there are changes produced by merge
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create pull request (review before apply)
        if: steps.merge.outputs.changed == 'true' && env.RUN_MODE == 'pr'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(sync): merge upstream ${{ env.UPSTREAM_REPO }}@${{ env.UPSTREAM_BRANCH }} (pref=${{ env.MERGE_PREFERENCE }})'
          branch: 'sync/upstream-${{ env.UPSTREAM_BRANCH }}'
          title: 'Sync upstream ${{ env.UPSTREAM_REPO }} → ${{ env.TARGET_BRANCH }} (pref=${{ env.MERGE_PREFERENCE }})'
          body: |
            Automated upstream sync:
            - Source: ${{ env.UPSTREAM_REPO }} @ ${{ env.UPSTREAM_BRANCH }}
            - Target: ${{ env.TARGET_BRANCH }}
            - Strategy: prefer "${{ env.MERGE_PREFERENCE }}" on conflicts

            This PR keeps your local changes intact on conflicts (when "ours" is selected).
            Review and merge if acceptable.
          labels: sync, upstream
          assignees: ${{ github.actor }}
          signoff: true

      - name: Push merge directly (no PR)
        if: steps.merge.outputs.changed == 'true' && env.RUN_MODE == 'push'
        run: |
          git push origin "${TARGET_BRANCH}"

      - name: No changes detected
        if: steps.merge.outputs.changed != 'true'
        run: echo "No upstream changes to merge."
